### ISSUE TITLE
4_2_2_3_structuralsimilaritybasedapproaches.md#基于结构相似性的方法

### ISSUE THREAD

**Issue by wangwei1237** [wangwei1237/digital_video_concepts#1]
4_2_2_3_structuralsimilaritybasedapproaches.md#基于结构相似性的方法
公式（4-6）之前的描述：**记下来**利用归一化信号**的**来计算结构比较函数。最后，结合这三个不同的结构产生一个整体的相似性度量结果。

应该改为：**接下来**利用归一化信号计算结构比较函数。最后，结合这三个不同的结构产生一个整体的相似性度量结果。

**Comment by GerenLiu** [comment]
fixed
